"""Tests for the v2.0.0 file-sync → plugin cutover (build-plan Chunk 9).

The cutover engine lives in the plugin's ``lib/migrate_plugin.py`` and is driven
through ``bin/prawduct-hook migrate-plugin``. These tests invoke it as a
subprocess (CLAUDE_PLUGIN_ROOT + CLAUDE_PROJECT_DIR), the established plugin-test
pattern — it exercises the real skill → hook → engine dispatch AND sidesteps the
``lib`` package-name collision (the framework's ``tools/lib`` and the plugin's
``lib`` share a name in-process).

The load-bearing guarantees under test:
  * REMOVE is registry-derived — only framework files go; the ~20 product skills
    and ~12 product tools a real consumer (hallucinote) intermixes are preserved.
  * The NEVER-TOUCH set (product ``.prawduct/`` state + all non-framework files)
    is byte-for-byte unchanged (the place-once contract, design §7).
  * Edit-in-place is surgical (CLAUDE.md block strip, settings merge preserving
    user keys, single distribution key appended).
  * Idempotent + safe-by-default (dry run unless --apply).
"""

from __future__ import annotations

import hashlib
import json
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
HOOK = ROOT / "bin" / "prawduct-hook"

# The 7 framework skills (registry-derived; mirrored here so the fixture is
# realistic — the engine derives this set itself, the test must not).
FRAMEWORK_SKILLS = [
    "critic", "pr", "janitor", "learnings", "backlog",
    "prawduct-advisory", "prawduct-doctor",
]
# Product skills a real consumer intermixes (hallucinote-shaped) — NEVER touched.
PRODUCT_SKILLS = ["compose-part", "mix-review", "song-new", "ableton-push"]
# Framework lib modules (a representative subset) — all removed.
FRAMEWORK_LIB = ["__init__.py", "core.py", "sync_cmd.py", "views.py", "migrate_cmd.py"]
# Product tool scripts living alongside the framework ones — NEVER touched.
PRODUCT_TOOLS = ["capture_cli.py", "song_eval.py", "melody_lens.py"]

# Product files whose bytes must be identical after migration.
PRODUCT_FILES = [
    ".prawduct/learnings.md",
    ".prawduct/learnings-detail.md",
    ".prawduct/backlog.md",
    ".prawduct/change-log.md",
    ".prawduct/artifacts/build-plan.md",
    ".prawduct/.critic-findings.json",
    "src/app.py",
    "tests/test_app.py",
    "README.md",
] + [f".claude/skills/{s}/SKILL.md" for s in PRODUCT_SKILLS] \
  + [f"tools/{t}" for t in PRODUCT_TOOLS]


# =============================================================================
# Fixture: a realistic file-sync consumer repo
# =============================================================================


def _w(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def make_filesync_repo(root: Path) -> Path:
    """Build a realistic file-sync consumer with framework + product files mixed."""
    # --- CLAUDE.md with framework block + the generator comments the template
    #     places around it + product content above/below ---
    _w(root / "CLAUDE.md",
       "# CLAUDE.md — MyProduct\n\n"
       "<!-- Generated by Prawduct. Content between PRAWDUCT markers is framework-managed. -->\n"
       "<!-- Add project-specific instructions above or below the markers. -->\n\n"
       "<!-- PRAWDUCT:BEGIN -->\n"
       "## Principles\nFramework governance text that the plugin now provides.\n"
       "<!-- PRAWDUCT:END -->\n\n"
       "## MyProduct-specific\nDon't touch this product instruction.\n")

    # --- settings.json: framework banner + hooks + USER hooks + permissions.
    #     SessionStart mixes a prawduct group AND a co-located user group (the
    #     real hallucinote shape) — only the prawduct group must be removed. ---
    _w(root / ".claude" / "settings.json", json.dumps({
        "companyAnnouncements": ["Built with Prawduct v1.8.1"],
        "permissions": {"allow": ["Bash(npm test:*)"]},
        "hooks": {
            "SessionStart": [
                {"matcher": "startup|clear|resume",
                 "hooks": [{"type": "command",
                            "command": 'python3 "$CLAUDE_PROJECT_DIR/tools/product-hook" clear'}]},
                {"matcher": "startup|clear|resume",
                 "hooks": [{"type": "command",
                            "command": 'bash "$CLAUDE_PROJECT_DIR/.claude/hooks/session-start.sh"'}]},
            ],
            "Stop": [{
                "matcher": "",
                "hooks": [{"type": "command",
                           "command": 'python3 "$CLAUDE_PROJECT_DIR/tools/product-hook" stop'}],
            }],
            "PreToolUse": [{
                "matcher": "Bash",
                "hooks": [{"type": "command", "command": "my-own-guard.sh"}],
            }],
        },
    }, indent=2) + "\n")

    # --- framework skills + product skills ---
    for s in FRAMEWORK_SKILLS:
        _w(root / ".claude" / "skills" / s / "SKILL.md", f"framework skill {s}\n")
    for s in PRODUCT_SKILLS:
        _w(root / ".claude" / "skills" / s / "SKILL.md", f"product skill {s}\n")

    # --- framework runtime + product tools ---
    _w(root / "tools" / "product-hook", "#!/usr/bin/env python3\n# framework hook\n")
    for m in FRAMEWORK_LIB:
        _w(root / "tools" / "lib" / m, f"# framework lib {m}\n")
    (root / "tools" / "lib" / "__pycache__").mkdir(parents=True, exist_ok=True)
    (root / "tools" / "lib" / "__pycache__" / "core.pyc").write_bytes(b"\x00bytecode")
    for t in PRODUCT_TOOLS:
        _w(root / "tools" / t, f"# product tool {t}\n")

    # --- .prawduct: framework protocol docs + product state ---
    _w(root / ".prawduct" / "critic-review.md", "framework critic protocol\n")
    _w(root / ".prawduct" / "pr-review.md", "framework pr protocol\n")
    _w(root / ".prawduct" / "build-governance.md", "framework build governance\n")
    _w(root / ".prawduct" / "sync-manifest.json", '{"files": {"tools/product-hook": "abc"}}\n')
    _w(root / ".prawduct" / "project-state.yaml",
       "# Project State\nbacklog_format_version: 2\nviews_enabled: true\n")
    _w(root / ".prawduct" / "learnings.md", "## A learning\nbody\n")
    _w(root / ".prawduct" / "learnings-detail.md", "detail\n")
    _w(root / ".prawduct" / "backlog.md", "# Backlog\n- item\n")
    _w(root / ".prawduct" / "change-log.md", "# Change Log\n")
    _w(root / ".prawduct" / "artifacts" / "build-plan.md", "# Build plan\n- [x] chunk\n")
    _w(root / ".prawduct" / ".critic-findings.json", '{"summary":"ok","findings":[]}\n')

    # --- product source/tests/docs ---
    _w(root / "src" / "app.py", "print('hi')\n")
    _w(root / "tests" / "test_app.py", "def test_x():\n    assert True\n")
    _w(root / "README.md", "# MyProduct\n")
    _w(root / ".gitignore", "__pycache__/\n.prawduct/.critic-findings.json\n")
    return root


def run_migrate(project_dir: Path, *flags: str) -> dict:
    """Invoke `bin/prawduct-hook migrate-plugin [flags] --json` as Claude would."""
    home = project_dir.parent / "_home"
    home.mkdir(exist_ok=True)
    env = {
        "HOME": str(home),
        "CLAUDE_PROJECT_DIR": str(project_dir),
        "CLAUDE_PLUGIN_ROOT": str(ROOT),
        "PATH": "/usr/bin:/bin:/usr/sbin:/sbin",
        "PYTHONDONTWRITEBYTECODE": "1",
    }
    proc = subprocess.run(
        [sys.executable, str(HOOK), "migrate-plugin", *flags, "--json"],
        capture_output=True, text=True, env=env, timeout=30,
    )
    assert proc.returncode == 0, f"migrate failed: {proc.stderr}\n{proc.stdout}"
    return json.loads(proc.stdout)


def _snapshot(root: Path, rels: list[str]) -> dict[str, str]:
    out = {}
    for rel in rels:
        p = root / rel
        if p.is_file():
            out[rel] = hashlib.sha256(p.read_bytes()).hexdigest()
    return out


@pytest.fixture
def repo(tmp_path: Path) -> Path:
    return make_filesync_repo(tmp_path / "myproduct")


# =============================================================================
# Dry run (default — safe)
# =============================================================================


def test_dry_run_plans_without_mutating(repo: Path):
    before = _snapshot(repo, PRODUCT_FILES)
    result = run_migrate(repo)  # no --apply

    assert result["applied"] is False
    assert result["already_migrated"] is False
    # Framework files are still on disk after a dry run.
    assert (repo / "tools" / "product-hook").is_file()
    assert (repo / ".claude" / "skills" / "critic" / "SKILL.md").is_file()
    assert (repo / ".prawduct" / "critic-review.md").is_file()
    # Product files untouched.
    assert _snapshot(repo, PRODUCT_FILES) == before
    # Plan names the framework files.
    assert "tools/product-hook" in result["removed"]
    assert ".prawduct/sync-manifest.json" in result["removed"]


def test_dry_run_plan_is_registry_derived(repo: Path):
    result = run_migrate(repo)
    removed = set(result["removed"])
    # All 7 framework skills + protocol docs + lib + hook in the plan.
    for s in FRAMEWORK_SKILLS:
        assert f".claude/skills/{s}/SKILL.md" in removed
    for doc in ("critic-review", "pr-review", "build-governance"):
        assert f".prawduct/{doc}.md" in removed
    for m in FRAMEWORK_LIB:
        assert f"tools/lib/{m}" in removed
    # No product skill / tool / state is ever in the REMOVE plan.
    for s in PRODUCT_SKILLS:
        assert f".claude/skills/{s}/SKILL.md" not in removed
    for t in PRODUCT_TOOLS:
        assert f"tools/{t}" not in removed
    assert not any(r.startswith(".prawduct/learnings") for r in removed)
    assert ".prawduct/backlog.md" not in removed
    # Edit-in-place files are NOT in the delete plan.
    assert "CLAUDE.md" not in removed
    assert ".claude/settings.json" not in removed


# =============================================================================
# Apply — removals
# =============================================================================


def test_apply_removes_framework_files(repo: Path):
    run_migrate(repo, "--apply")

    assert not (repo / "tools" / "product-hook").exists()
    assert not (repo / "tools" / "lib").exists()  # dir removed when empty
    assert not (repo / ".prawduct" / "sync-manifest.json").exists()
    for doc in ("critic-review", "pr-review", "build-governance"):
        assert not (repo / ".prawduct" / f"{doc}.md").exists()
    for s in FRAMEWORK_SKILLS:
        assert not (repo / ".claude" / "skills" / s).exists()  # whole dir gone


def test_apply_preserves_all_product_files_byte_for_byte(repo: Path):
    # The acceptance contract: zero changes to the NEVER-TOUCH set.
    before = _snapshot(repo, PRODUCT_FILES)
    run_migrate(repo, "--apply")
    after = _snapshot(repo, PRODUCT_FILES)
    assert after == before, "a product file changed during migration"
    # And every product file still exists.
    assert set(after.keys()) == set(before.keys())


def test_product_skill_and_tool_dirs_survive(repo: Path):
    run_migrate(repo, "--apply")
    for s in PRODUCT_SKILLS:
        assert (repo / ".claude" / "skills" / s / "SKILL.md").is_file()
    for t in PRODUCT_TOOLS:
        assert (repo / "tools" / t).is_file()
    # tools/ itself survives (it still holds product scripts).
    assert (repo / "tools").is_dir()


# =============================================================================
# Apply — edit-in-place
# =============================================================================


def test_claude_block_stripped_product_content_kept(repo: Path):
    run_migrate(repo, "--apply")
    text = (repo / "CLAUDE.md").read_text()
    assert "PRAWDUCT:BEGIN" not in text
    assert "PRAWDUCT:END" not in text
    assert "Framework governance text" not in text
    # The framework generator comments that bracketed the block are gone too —
    # otherwise they dangle a reference to markers that no longer exist.
    assert "Generated by Prawduct" not in text
    assert "above or below the markers" not in text
    # Product content above and below the block is intact.
    assert "# CLAUDE.md — MyProduct" in text
    assert "Don't touch this product instruction." in text


def test_settings_mixed_sessionstart_keeps_only_user_group(repo: Path):
    # The hallucinote shape: SessionStart has a prawduct group AND a user group.
    run_migrate(repo, "--apply")
    data = json.loads((repo / ".claude" / "settings.json").read_text())
    ss = data["hooks"]["SessionStart"]
    assert len(ss) == 1, "the prawduct SessionStart group must be removed, the user group kept"
    assert "session-start.sh" in ss[0]["hooks"][0]["command"]
    assert all("product-hook" not in g["hooks"][0]["command"] for g in ss)


def test_settings_transformed_and_user_keys_preserved(repo: Path):
    run_migrate(repo, "--apply")
    data = json.loads((repo / ".claude" / "settings.json").read_text())

    # Framework banner removed; the prawduct Stop group removed entirely.
    assert "companyAnnouncements" not in data
    assert "Stop" not in data.get("hooks", {})
    # No surviving hook anywhere still invokes the legacy product-hook.
    for groups in data.get("hooks", {}).values():
        for group in groups:
            for h in group.get("hooks", []):
                assert "product-hook" not in h.get("command", "")
    # USER hooks preserved (the co-located SessionStart user group + PreToolUse).
    assert "SessionStart" in data["hooks"]
    assert data["hooks"]["PreToolUse"][0]["hooks"][0]["command"] == "my-own-guard.sh"
    # USER permissions preserved.
    assert data["permissions"] == {"allow": ["Bash(npm test:*)"]}
    # Install reference added, pinned to ref:main + autoUpdate (design §8/§5b).
    mkt = data["extraKnownMarketplaces"]["prawduct"]
    assert mkt["source"] == {"source": "github", "repo": "brookstalley/prawduct", "ref": "main"}
    assert mkt["autoUpdate"] is True
    assert data["enabledPlugins"]["prawduct@prawduct"] is True


def test_settings_preserves_other_marketplaces_and_plugins(repo: Path):
    # A repo that already references another marketplace/plugin keeps them.
    settings = repo / ".claude" / "settings.json"
    data = json.loads(settings.read_text())
    data["extraKnownMarketplaces"] = {"other": {"source": {"source": "github", "repo": "x/y"}}}
    data["enabledPlugins"] = {"other@other": True}
    settings.write_text(json.dumps(data, indent=2) + "\n")

    run_migrate(repo, "--apply")
    data = json.loads(settings.read_text())
    assert "other" in data["extraKnownMarketplaces"]
    assert "prawduct" in data["extraKnownMarketplaces"]
    assert data["enabledPlugins"]["other@other"] is True
    assert data["enabledPlugins"]["prawduct@prawduct"] is True


def test_distribution_recorded_state_preserved(repo: Path):
    original = (repo / ".prawduct" / "project-state.yaml").read_text()
    run_migrate(repo, "--apply")
    updated = (repo / ".prawduct" / "project-state.yaml").read_text()
    # Original content preserved verbatim as a prefix; only the marker appended.
    assert updated.startswith(original)
    assert "distribution: plugin" in updated
    # The pre-existing product keys are untouched.
    assert "backlog_format_version: 2" in updated
    assert "views_enabled: true" in updated


def test_marker_gitignored(repo: Path):
    run_migrate(repo, "--apply")
    gi = (repo / ".gitignore").read_text().splitlines()
    assert ".prawduct/.prawduct-version" in gi
    # Pre-existing entries preserved.
    assert "__pycache__/" in gi


# =============================================================================
# Idempotency + backward compat
# =============================================================================


def test_apply_is_idempotent(repo: Path):
    run_migrate(repo, "--apply")
    snap = _snapshot(repo, PRODUCT_FILES + ["CLAUDE.md", ".claude/settings.json",
                                            ".prawduct/project-state.yaml"])
    result = run_migrate(repo, "--apply")  # second run
    assert result["already_migrated"] is True
    assert result["removed"] == []
    assert result["edited"] == []
    after = _snapshot(repo, PRODUCT_FILES + ["CLAUDE.md", ".claude/settings.json",
                                             ".prawduct/project-state.yaml"])
    assert after == snap, "second migrate mutated the repo"


def test_already_migrated_dry_run_is_noop(repo: Path):
    # A repo that already declares plugin distribution: no plan, no changes.
    state = repo / ".prawduct" / "project-state.yaml"
    state.write_text(state.read_text() + "distribution: plugin\n")
    result = run_migrate(repo)
    assert result["already_migrated"] is True
    assert result["removed"] == []
    # Framework files left in place (the engine refuses to act).
    assert (repo / "tools" / "product-hook").is_file()


def test_partial_framework_files_migrate_cleanly(repo: Path):
    # A repo missing some framework files (e.g. no pr-review.md) still migrates;
    # only present files are removed, no error.
    (repo / ".prawduct" / "pr-review.md").unlink()
    result = run_migrate(repo, "--apply")
    assert ".prawduct/pr-review.md" not in result["removed"]
    assert ".prawduct/critic-review.md" in result["removed"]
    assert not (repo / "tools" / "product-hook").exists()


def test_no_settings_file_creates_install_reference(repo: Path):
    # An odd repo with no settings.json still gets a valid install reference.
    (repo / ".claude" / "settings.json").unlink()
    run_migrate(repo, "--apply")
    data = json.loads((repo / ".claude" / "settings.json").read_text())
    assert data["enabledPlugins"]["prawduct@prawduct"] is True


# =============================================================================
# Structural — skill + dispatch wiring
# =============================================================================


def test_migrate_skill_exists_and_is_scoped():
    skill = ROOT / "skills" / "migrate" / "SKILL.md"
    assert skill.is_file(), "skills/migrate/SKILL.md must exist (the /prawduct:migrate entry)"
    text = skill.read_text()
    assert "user-invocable: true" in text
    # Scoped to the cutover subcommand + git, not arbitrary Bash.
    assert "Bash(prawduct-hook migrate-plugin*)" in text
    assert "Bash(...)" not in text and "Bash(*)" not in text


def test_hook_dispatches_migrate_plugin():
    src = HOOK.read_text()
    assert 'command == "migrate-plugin"' in src
    assert "migrate-plugin [--apply] [--json]" in src  # usage string


def test_migrate_nudges_point_at_existing_skill():
    # Chunk 8's nudges reference /prawduct:migrate — the skill must now back them.
    assert (ROOT / "skills" / "migrate" / "SKILL.md").is_file()
    assert "/prawduct:migrate" in (ROOT / "bin" / "prawduct-hook").read_text()
