"""Tests for the v2.0.0 file-sync → plugin cutover (build-plan Chunk 9).

The cutover engine lives in the plugin's ``lib/migrate_plugin.py`` and is driven
through ``bin/prawduct-hook migrate-plugin``. These tests invoke it as a
subprocess (CLAUDE_PLUGIN_ROOT + CLAUDE_PROJECT_DIR), the established plugin-test
pattern — it exercises the real skill → hook → engine dispatch AND sidesteps the
``lib`` package-name collision (the framework's ``tools/lib`` and the plugin's
``lib`` share a name in-process).

The load-bearing guarantees under test:
  * REMOVE is registry-derived — only framework files go; the ~20 product skills
    and ~12 product tools a real consumer (hallucinote) intermixes are preserved.
  * The NEVER-TOUCH set (product ``.prawduct/`` state + all non-framework files)
    is byte-for-byte unchanged (the place-once contract, design §7).
  * Edit-in-place is surgical (CLAUDE.md block strip, settings merge preserving
    user keys, single distribution key appended).
  * Idempotent + safe-by-default (dry run unless --apply).
"""

from __future__ import annotations

import ast
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent / "plugin"
HOOK = ROOT / "bin" / "prawduct-hook"

# TestCollapseBlankRuns imports the engine DIRECTLY (in-process), unlike the rest
# of this file which subprocesses bin/prawduct-hook. The direct import keeps the
# pure-helper unit tests isolated and fast; sys.path + ``from lib import ...``
# mirrors the established pattern in the sibling lib tests (test_advisory_store.py).
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from lib import migrate_plugin as _migrate_plugin  # noqa: E402 — sys.path mutated above

# The 7 framework skills (registry-derived; mirrored here so the fixture is
# realistic — the engine derives this set itself, the test must not).
FRAMEWORK_SKILLS = [
    "critic", "pr", "janitor", "learnings", "backlog",
    "prawduct-advisory", "prawduct-doctor",
]
# Product skills a real consumer intermixes (hallucinote-shaped) — NEVER touched.
PRODUCT_SKILLS = ["compose-part", "mix-review", "song-new", "ableton-push"]
# Framework lib modules (a representative subset) — all removed.
FRAMEWORK_LIB = ["__init__.py", "core.py", "sync_cmd.py", "views.py", "migrate_cmd.py"]
# Product tool scripts living alongside the framework ones — NEVER touched.
PRODUCT_TOOLS = ["capture_cli.py", "song_eval.py", "melody_lens.py"]

# Product files whose bytes must be identical after migration.
PRODUCT_FILES = [
    ".prawduct/learnings.md",
    ".prawduct/learnings-detail.md",
    ".prawduct/backlog.md",
    ".prawduct/change-log.md",
    ".prawduct/artifacts/build-plan.md",
    ".prawduct/.critic-findings.json",
    "src/app.py",
    "tests/test_app.py",
    "README.md",
] + [f".claude/skills/{s}/SKILL.md" for s in PRODUCT_SKILLS] \
  + [f"tools/{t}" for t in PRODUCT_TOOLS]


# =============================================================================
# Fixture: a realistic file-sync consumer repo
# =============================================================================


def _w(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def make_filesync_repo(root: Path) -> Path:
    """Build a realistic file-sync consumer with framework + product files mixed."""
    # --- CLAUDE.md with framework block + the generator comments the template
    #     places around it + product content above/below ---
    _w(root / "CLAUDE.md",
       "# CLAUDE.md — MyProduct\n\n"
       "<!-- Generated by Prawduct. Content between PRAWDUCT markers is framework-managed. -->\n"
       "<!-- Add project-specific instructions above or below the markers. -->\n\n"
       "<!-- PRAWDUCT:BEGIN -->\n"
       "## Principles\nFramework governance text that the plugin now provides.\n"
       "<!-- PRAWDUCT:END -->\n\n"
       "## MyProduct-specific\nDon't touch this product instruction.\n")

    # --- settings.json: framework banner + hooks + USER hooks + permissions.
    #     SessionStart mixes a prawduct group AND a co-located user group (the
    #     real hallucinote shape) — only the prawduct group must be removed. ---
    _w(root / ".claude" / "settings.json", json.dumps({
        "companyAnnouncements": ["Built with Prawduct v1.8.1"],
        "permissions": {"allow": ["Bash(npm test:*)"]},
        "hooks": {
            "SessionStart": [
                {"matcher": "startup|clear|resume",
                 "hooks": [{"type": "command",
                            "command": 'python3 "$CLAUDE_PROJECT_DIR/tools/product-hook" clear'}]},
                {"matcher": "startup|clear|resume",
                 "hooks": [{"type": "command",
                            "command": 'bash "$CLAUDE_PROJECT_DIR/.claude/hooks/session-start.sh"'}]},
            ],
            "Stop": [{
                "matcher": "",
                "hooks": [{"type": "command",
                           "command": 'python3 "$CLAUDE_PROJECT_DIR/tools/product-hook" stop'}],
            }],
            "PreToolUse": [{
                "matcher": "Bash",
                "hooks": [{"type": "command", "command": "my-own-guard.sh"}],
            }],
        },
    }, indent=2) + "\n")

    # --- framework skills + product skills ---
    for s in FRAMEWORK_SKILLS:
        _w(root / ".claude" / "skills" / s / "SKILL.md", f"framework skill {s}\n")
    for s in PRODUCT_SKILLS:
        _w(root / ".claude" / "skills" / s / "SKILL.md", f"product skill {s}\n")

    # --- framework runtime + product tools ---
    _w(root / "tools" / "product-hook", "#!/usr/bin/env python3\n# framework hook\n")
    for m in FRAMEWORK_LIB:
        _w(root / "tools" / "lib" / m, f"# framework lib {m}\n")
    (root / "tools" / "lib" / "__pycache__").mkdir(parents=True, exist_ok=True)
    (root / "tools" / "lib" / "__pycache__" / "core.pyc").write_bytes(b"\x00bytecode")
    for t in PRODUCT_TOOLS:
        _w(root / "tools" / t, f"# product tool {t}\n")

    # --- .prawduct: framework protocol docs + product state ---
    _w(root / ".prawduct" / "critic-review.md", "framework critic protocol\n")
    _w(root / ".prawduct" / "pr-review.md", "framework pr protocol\n")
    _w(root / ".prawduct" / "build-governance.md", "framework build governance\n")
    _w(root / ".prawduct" / "sync-manifest.json", '{"files": {"tools/product-hook": "abc"}}\n')
    _w(root / ".prawduct" / "project-state.yaml",
       "# Project State\nbacklog_format_version: 2\nviews_enabled: true\n")
    _w(root / ".prawduct" / "learnings.md", "## A learning\nbody\n")
    _w(root / ".prawduct" / "learnings-detail.md", "detail\n")
    _w(root / ".prawduct" / "backlog.md", "# Backlog\n- item\n")
    _w(root / ".prawduct" / "change-log.md", "# Change Log\n")
    _w(root / ".prawduct" / "artifacts" / "build-plan.md", "# Build plan\n- [x] chunk\n")
    _w(root / ".prawduct" / ".critic-findings.json", '{"summary":"ok","findings":[]}\n')

    # --- product source/tests/docs ---
    _w(root / "src" / "app.py", "print('hi')\n")
    _w(root / "tests" / "test_app.py", "def test_x():\n    assert True\n")
    _w(root / "README.md", "# MyProduct\n")
    _w(root / ".gitignore", "__pycache__/\n.prawduct/.critic-findings.json\n")
    return root


def run_migrate(project_dir: Path, *flags: str) -> dict:
    """Invoke `bin/prawduct-hook migrate-plugin [flags] --json` as Claude would."""
    home = project_dir.parent / "_home"
    home.mkdir(exist_ok=True)
    env = {
        "HOME": str(home),
        "CLAUDE_PROJECT_DIR": str(project_dir),
        "CLAUDE_PLUGIN_ROOT": str(ROOT),
        "PATH": "/usr/bin:/bin:/usr/sbin:/sbin",
        "PYTHONDONTWRITEBYTECODE": "1",
    }
    proc = subprocess.run(
        [sys.executable, str(HOOK), "migrate-plugin", *flags, "--json"],
        capture_output=True, text=True, env=env, timeout=30,
    )
    assert proc.returncode == 0, f"migrate failed: {proc.stderr}\n{proc.stdout}"
    return json.loads(proc.stdout)


def _snapshot(root: Path, rels: list[str]) -> dict[str, str]:
    out = {}
    for rel in rels:
        p = root / rel
        if p.is_file():
            out[rel] = hashlib.sha256(p.read_bytes()).hexdigest()
    return out


@pytest.fixture
def repo(tmp_path: Path) -> Path:
    return make_filesync_repo(tmp_path / "myproduct")


# =============================================================================
# Dry run (default — safe)
# =============================================================================


def test_dry_run_plans_without_mutating(repo: Path):
    before = _snapshot(repo, PRODUCT_FILES)
    result = run_migrate(repo)  # no --apply

    assert result["applied"] is False
    assert result["already_migrated"] is False
    # Framework files are still on disk after a dry run.
    assert (repo / "tools" / "product-hook").is_file()
    assert (repo / ".claude" / "skills" / "critic" / "SKILL.md").is_file()
    assert (repo / ".prawduct" / "critic-review.md").is_file()
    # Product files untouched.
    assert _snapshot(repo, PRODUCT_FILES) == before
    # Plan names the framework files.
    assert "tools/product-hook" in result["removed"]
    assert ".prawduct/sync-manifest.json" in result["removed"]


def test_dry_run_plan_is_registry_derived(repo: Path):
    result = run_migrate(repo)
    removed = set(result["removed"])
    # All 7 framework skills + protocol docs + lib + hook in the plan.
    for s in FRAMEWORK_SKILLS:
        assert f".claude/skills/{s}/SKILL.md" in removed
    for doc in ("critic-review", "pr-review", "build-governance"):
        assert f".prawduct/{doc}.md" in removed
    for m in FRAMEWORK_LIB:
        assert f"tools/lib/{m}" in removed
    # No product skill / tool / state is ever in the REMOVE plan.
    for s in PRODUCT_SKILLS:
        assert f".claude/skills/{s}/SKILL.md" not in removed
    for t in PRODUCT_TOOLS:
        assert f"tools/{t}" not in removed
    assert not any(r.startswith(".prawduct/learnings") for r in removed)
    assert ".prawduct/backlog.md" not in removed
    # Edit-in-place files are NOT in the delete plan.
    assert "CLAUDE.md" not in removed
    assert ".claude/settings.json" not in removed


# =============================================================================
# Apply — removals
# =============================================================================


def test_apply_removes_framework_files(repo: Path):
    run_migrate(repo, "--apply")

    assert not (repo / "tools" / "product-hook").exists()
    assert not (repo / "tools" / "lib").exists()  # dir removed when empty
    assert not (repo / ".prawduct" / "sync-manifest.json").exists()
    for doc in ("critic-review", "pr-review", "build-governance"):
        assert not (repo / ".prawduct" / f"{doc}.md").exists()
    for s in FRAMEWORK_SKILLS:
        assert not (repo / ".claude" / "skills" / s).exists()  # whole dir gone


def test_apply_preserves_all_product_files_byte_for_byte(repo: Path):
    # The acceptance contract: zero changes to the NEVER-TOUCH set.
    before = _snapshot(repo, PRODUCT_FILES)
    run_migrate(repo, "--apply")
    after = _snapshot(repo, PRODUCT_FILES)
    assert after == before, "a product file changed during migration"
    # And every product file still exists.
    assert set(after.keys()) == set(before.keys())


def test_product_skill_and_tool_dirs_survive(repo: Path):
    run_migrate(repo, "--apply")
    for s in PRODUCT_SKILLS:
        assert (repo / ".claude" / "skills" / s / "SKILL.md").is_file()
    for t in PRODUCT_TOOLS:
        assert (repo / "tools" / t).is_file()
    # tools/ itself survives (it still holds product scripts).
    assert (repo / "tools").is_dir()


# =============================================================================
# Apply — edit-in-place
# =============================================================================


def test_claude_block_stripped_product_content_kept(repo: Path):
    run_migrate(repo, "--apply")
    text = (repo / "CLAUDE.md").read_text()
    assert "PRAWDUCT:BEGIN" not in text
    assert "PRAWDUCT:END" not in text
    assert "Framework governance text" not in text
    # The framework generator comments that bracketed the block are gone too —
    # otherwise they dangle a reference to markers that no longer exist.
    assert "Generated by Prawduct" not in text
    assert "above or below the markers" not in text
    # Product content above and below the block is intact.
    assert "# CLAUDE.md — MyProduct" in text
    assert "Don't touch this product instruction." in text


def test_settings_mixed_sessionstart_keeps_only_user_group(repo: Path):
    # The hallucinote shape: SessionStart has a prawduct group AND a user group.
    run_migrate(repo, "--apply")
    data = json.loads((repo / ".claude" / "settings.json").read_text())
    ss = data["hooks"]["SessionStart"]
    assert len(ss) == 1, "the prawduct SessionStart group must be removed, the user group kept"
    assert "session-start.sh" in ss[0]["hooks"][0]["command"]
    assert all("product-hook" not in g["hooks"][0]["command"] for g in ss)


def test_settings_transformed_and_user_keys_preserved(repo: Path):
    run_migrate(repo, "--apply")
    data = json.loads((repo / ".claude" / "settings.json").read_text())

    # Framework banner removed; the prawduct Stop group removed entirely.
    assert "companyAnnouncements" not in data
    assert "Stop" not in data.get("hooks", {})
    # No surviving hook anywhere still invokes the legacy product-hook.
    for groups in data.get("hooks", {}).values():
        for group in groups:
            for h in group.get("hooks", []):
                assert "product-hook" not in h.get("command", "")
    # USER hooks preserved (the co-located SessionStart user group + PreToolUse).
    assert "SessionStart" in data["hooks"]
    assert data["hooks"]["PreToolUse"][0]["hooks"][0]["command"] == "my-own-guard.sh"
    # USER permissions preserved.
    assert data["permissions"] == {"allow": ["Bash(npm test:*)"]}
    # Install reference added, pinned to ref:main + autoUpdate (design §8/§5b).
    mkt = data["extraKnownMarketplaces"]["prawduct"]
    assert mkt["source"] == {"source": "github", "repo": "brookstalley/prawduct", "ref": "main"}
    assert mkt["autoUpdate"] is True
    assert data["enabledPlugins"]["prawduct@prawduct"] is True


def test_settings_preserves_other_marketplaces_and_plugins(repo: Path):
    # A repo that already references another marketplace/plugin keeps them.
    settings = repo / ".claude" / "settings.json"
    data = json.loads(settings.read_text())
    data["extraKnownMarketplaces"] = {"other": {"source": {"source": "github", "repo": "x/y"}}}
    data["enabledPlugins"] = {"other@other": True}
    settings.write_text(json.dumps(data, indent=2) + "\n")

    run_migrate(repo, "--apply")
    data = json.loads(settings.read_text())
    assert "other" in data["extraKnownMarketplaces"]
    assert "prawduct" in data["extraKnownMarketplaces"]
    assert data["enabledPlugins"]["other@other"] is True
    assert data["enabledPlugins"]["prawduct@prawduct"] is True


def test_distribution_recorded_and_product_keys_preserved(repo: Path):
    """Preserve-verbatim protects what the PRODUCT authored — not framework residue.

    This test used to assert ``updated.startswith(original)`` and call
    ``views_enabled`` a "pre-existing product key". It is not one: it is a
    retired *framework* key, written by the derived-view model, and removing it
    is the entire reason ``lib/lifecycle_repair.py`` exists. The old assertion
    pinned a misclassification, so the cutover — the one act that already deletes
    every other framework file — was obliged to carry framework residue forward.
    That is how these keys reached the plugin era in ten products.

    The contract is now stated on the axis that actually matters: product keys
    survive byte-for-byte, retired framework keys go, and the marker is appended.
    """
    run_migrate(repo, "--apply")
    updated = (repo / ".prawduct" / "project-state.yaml").read_text()

    assert "distribution: plugin" in updated
    # What the product authored is untouched.
    assert "# Project State" in updated
    assert "backlog_format_version: 2" in updated
    # What a retired framework mechanism wrote is not.
    assert "views_enabled" not in updated


def test_cutover_strips_the_retired_test_tracking_block(repo: Path):
    """The cutover is the last moment this residue is cheap to remove.

    After it, the repo is a plugin consumer and the only route left is the
    operator running `/prawduct:doctor` — which ten products never did, because
    nothing told them there was anything to converge.
    """
    state = repo / ".prawduct" / "project-state.yaml"
    state.write_text(
        state.read_text()
        + "\nbuild_state:\n"
        '  source_root: "src/"\n'
        "  test_tracking:\n"
        "    test_count: 1724\n"
        "    test_files: 118\n"
        "    history:\n"
        "      - tests_added: 24\n"
        "        date: 2026-08-14\n"
        "  spec_compliance: partial\n",
        encoding="utf-8",
    )
    result = run_migrate(repo, "--apply")
    updated = state.read_text()

    for gone in ("test_tracking", "test_count", "test_files", "tests_added"):
        assert gone not in updated, f"{gone} survived the cutover"
    assert 'source_root: "src/"' in updated, "took a sibling with it"
    assert "spec_compliance: partial" in updated
    assert "build_state.test_tracking" in result["state_keys_removed"]


def test_dry_run_names_the_state_keys_and_writes_nothing(repo: Path):
    """The operator's single confirmation has to name the blast radius, so the
    removal must appear in the plan — not only in the result of doing it."""
    state = repo / ".prawduct" / "project-state.yaml"
    before = state.read_text()

    result = run_migrate(repo)  # no --apply

    assert "views_enabled" in result["state_keys_removed"]
    assert ".prawduct/project-state.yaml" in result["edited"]
    assert state.read_text() == before, "dry run wrote to the state file"


def test_a_state_file_with_no_retired_keys_is_left_alone(tmp_path: Path):
    """No retired key means the only state edit is the appended marker."""
    root = make_filesync_repo(tmp_path)
    state = root / ".prawduct" / "project-state.yaml"
    state.write_text("# Project State\nbacklog_format_version: 2\n", encoding="utf-8")
    original = state.read_text()

    result = run_migrate(root, "--apply")

    assert result["state_keys_removed"] == []
    assert state.read_text().startswith(original), "rewrote a file it had nothing to fix"


def test_a_repo_with_no_state_file_does_not_error(tmp_path: Path):
    """Carried from Chunk 01's Critic review (R-4), closing AC9's second half.

    The path is already safe twice over — both `strip_state_file` and
    `retired_state_keys` check `is_file()` *and* catch `OSError` — so this pins a
    guard rather than fixing a defect. It rides this chunk's commit because a
    deferral to a later review round costs a round, and riding a commit already
    being made costs none.
    """
    root = make_filesync_repo(tmp_path)
    (root / ".prawduct" / "project-state.yaml").unlink()

    result = run_migrate(root, "--apply")

    assert result["state_keys_removed"] == []
    # `record_distribution` creates the file, so the cutover still completes.
    assert (root / ".prawduct" / "project-state.yaml").is_file()


def test_the_cutover_owns_no_copy_of_what_a_retired_key_is(repo: Path):
    """One home for the fact, checked mechanically rather than by convention.

    ``lifecycle-repair`` converges repos that cut over before this removal
    existed; the cutover removes the same keys on the way through. Two callers,
    one definition — a second copy here would drift the moment either changed.
    """
    tree = ast.parse((ROOT / "lib" / "migrate_plugin.py").read_text())

    # Docstrings are exempt: prose naming what gets removed helps a reader and
    # cannot drift into behaviour. What must not exist is a *literal the code
    # acts on* — that is the copy that goes stale silently.
    docstrings = {
        node.body[0].value
        for node in ast.walk(tree)
        if isinstance(
            node, (ast.Module, ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)
        )
        and node.body
        and isinstance(node.body[0], ast.Expr)
        and isinstance(node.body[0].value, ast.Constant)
        and isinstance(node.body[0].value.value, str)
    }
    live_strings = [
        node.value
        for node in ast.walk(tree)
        if isinstance(node, ast.Constant)
        and isinstance(node.value, str)
        and node not in docstrings
    ]

    for key_name in ("views_enabled", "scope_rollups", "test_tracking"):
        offenders = [s for s in live_strings if key_name in s]
        assert not offenders, (
            f"migrate_plugin has a live string naming {key_name!r} ({offenders!r}) "
            "— the key set belongs to lifecycle_repair, which both entry points call"
        )


def test_marker_gitignored(repo: Path):
    run_migrate(repo, "--apply")
    gi = (repo / ".gitignore").read_text().splitlines()
    assert ".prawduct/.prawduct-version" in gi
    # Pre-existing entries preserved.
    assert "__pycache__/" in gi


# =============================================================================
# Chunk 10 — thin static CLAUDE.md anchor (design §4)
# =============================================================================


def test_anchor_inserted_in_place_of_block(repo: Path):
    # Stripping the heavy block leaves the thin static anchor behind, in place.
    run_migrate(repo, "--apply")
    text = (repo / "CLAUDE.md").read_text()
    # The block is gone; the anchor (with its own distinct marker) is present.
    assert "PRAWDUCT:BEGIN" not in text and "PRAWDUCT:END" not in text
    assert "PRAWDUCT:ANCHOR" in text
    # The few hardest rules + the plugin pointer (design §4).
    assert "/prawduct:methodology building" in text  # read the build cycle before code
    assert "governed by **Prawduct**" in text    # this repo is plugin-governed
    assert "Stop hook" in text and "session end" in text  # enforcement at session end
    # CLAUDE.md is reported as an edit.
    result = run_migrate(repo)  # already migrated now → dry run is a no-op
    assert result["already_migrated"] is True


def test_anchor_sits_between_product_content(repo: Path):
    # Document shape preserved: product title → governance anchor → product body.
    run_migrate(repo, "--apply")
    text = (repo / "CLAUDE.md").read_text()
    i_title = text.index("# CLAUDE.md — MyProduct")
    i_anchor = text.index("PRAWDUCT:ANCHOR")
    i_product = text.index("Don't touch this product instruction.")
    assert i_title < i_anchor < i_product, "anchor must land where the block was"


def test_anchor_is_version_free(repo: Path):
    # The anchor carries NO version (the banner injects it at runtime, §4). The
    # fixture's product content is version-free, so any version-like token in the
    # migrated CLAUDE.md would originate from the framework-authored anchor.
    run_migrate(repo, "--apply")
    text = (repo / "CLAUDE.md").read_text()
    current_version = (Path(__file__).resolve().parents[1] / "plugin" / "VERSION").read_text().strip()
    assert current_version not in text, "the current framework version must not be baked in"
    assert re.search(r"\bv?\d+\.\d+", text) is None, "anchor must not embed a version number"


def test_anchor_not_duplicated_on_reapply(repo: Path):
    # Anchor insertion is idempotent independent of the already_migrated guard:
    # if the distribution marker is absent (partial/reverted state) migrate runs
    # the full apply again, and the anchor must NOT be inserted twice.
    run_migrate(repo, "--apply")
    state = repo / ".prawduct" / "project-state.yaml"
    state.write_text("".join(
        ln + "\n" for ln in state.read_text().splitlines()
        if "distribution: plugin" not in ln
    ))
    first = (repo / "CLAUDE.md").read_text()

    result = run_migrate(repo, "--apply")  # already_migrated is now False again
    assert result["already_migrated"] is False
    assert "CLAUDE.md" not in result["edited"], "anchor already present → not re-edited"
    text = (repo / "CLAUDE.md").read_text()
    assert text == first, "re-apply must not mutate an already-anchored CLAUDE.md"
    assert text.count("PRAWDUCT:ANCHOR") == 1
    assert text.count("## Governance (Prawduct)") == 1


def test_dry_run_lists_claude_edit_when_anchor_missing(tmp_path: Path):
    # A repo whose CLAUDE.md has neither a block nor the anchor: the dry-run plan
    # still lists CLAUDE.md as an edit (the anchor must be inserted), and apply
    # appends the anchor while preserving the existing content.
    root = make_filesync_repo(tmp_path / "noblock")
    (root / "CLAUDE.md").write_text("# CLAUDE.md — NoBlock\n\n## Only product content\n")

    plan = run_migrate(root)
    assert "CLAUDE.md" in plan["edited"]

    run_migrate(root, "--apply")
    text = (root / "CLAUDE.md").read_text()
    assert "PRAWDUCT:ANCHOR" in text
    assert "## Only product content" in text  # pre-existing content kept


def test_migrated_claude_has_no_leading_double_blank(tmp_path: Path):
    # MIG-8C3V: when the framework generator comments sit BETWEEN the H1 and the
    # first product section (the ../discodon shape), dropping those comment lines
    # left the blank line before them adjacent to the blank line after them — a
    # triple-newline run = a double blank line between the H1 and the first
    # product section. Cosmetic, but a wart in a diff meant to be pristine.
    root = make_filesync_repo(tmp_path / "discodon")
    (root / "CLAUDE.md").write_text(
        "# CLAUDE.md — Discodon\n\n"
        "<!-- Generated by Prawduct. Content between PRAWDUCT markers is framework-managed. -->\n"
        "<!-- Add project-specific instructions above or below the markers. -->\n\n"
        "Product intro paragraph.\n\n"
        "<!-- PRAWDUCT:BEGIN -->\n"
        "## Principles\nFramework governance text the plugin now provides.\n"
        "<!-- PRAWDUCT:END -->\n\n"
        "## Discodon-specific\nDon't touch this product instruction.\n",
        encoding="utf-8",
    )

    run_migrate(root, "--apply")
    text = (root / "CLAUDE.md").read_text()

    # The generator comments are gone, and product content is preserved.
    assert "Generated by Prawduct" not in text
    assert "Product intro paragraph." in text
    # No run of 3+ newlines anywhere (no double blank line in the assembled file).
    assert "\n\n\n" not in text, "migrated CLAUDE.md has a double blank line (triple-newline run)"
    # Specifically: no double blank between the H1 and the first product section.
    i_title = text.index("# CLAUDE.md — Discodon")
    i_first_section = text.index("Product intro paragraph.")
    between = text[i_title:i_first_section]
    assert "\n\n\n" not in between, "double blank line between the H1 and the first product section"


# =============================================================================
# Idempotency + backward compat
# =============================================================================


def test_apply_is_idempotent(repo: Path):
    run_migrate(repo, "--apply")
    snap = _snapshot(repo, PRODUCT_FILES + ["CLAUDE.md", ".claude/settings.json",
                                            ".prawduct/project-state.yaml"])
    result = run_migrate(repo, "--apply")  # second run
    assert result["already_migrated"] is True
    assert result["removed"] == []
    assert result["edited"] == []
    after = _snapshot(repo, PRODUCT_FILES + ["CLAUDE.md", ".claude/settings.json",
                                             ".prawduct/project-state.yaml"])
    assert after == snap, "second migrate mutated the repo"


def test_already_migrated_dry_run_is_noop(repo: Path):
    # A repo that already declares plugin distribution: no plan, no changes.
    state = repo / ".prawduct" / "project-state.yaml"
    state.write_text(state.read_text() + "distribution: plugin\n")
    result = run_migrate(repo)
    assert result["already_migrated"] is True
    assert result["removed"] == []
    # Framework files left in place (the engine refuses to act).
    assert (repo / "tools" / "product-hook").is_file()


def test_partial_framework_files_migrate_cleanly(repo: Path):
    # A repo missing some framework files (e.g. no pr-review.md) still migrates;
    # only present files are removed, no error.
    (repo / ".prawduct" / "pr-review.md").unlink()
    result = run_migrate(repo, "--apply")
    assert ".prawduct/pr-review.md" not in result["removed"]
    assert ".prawduct/critic-review.md" in result["removed"]
    assert not (repo / "tools" / "product-hook").exists()


def test_no_settings_file_creates_install_reference(repo: Path):
    # An odd repo with no settings.json still gets a valid install reference.
    (repo / ".claude" / "settings.json").unlink()
    run_migrate(repo, "--apply")
    data = json.loads((repo / ".claude" / "settings.json").read_text())
    assert data["enabledPlugins"]["prawduct@prawduct"] is True


# =============================================================================
# Structural — skill + dispatch wiring
# =============================================================================


def test_migrate_skill_exists_and_is_scoped():
    skill = ROOT / "skills" / "migrate" / "SKILL.md"
    assert skill.is_file(), "skills/migrate/SKILL.md must exist (the /prawduct:migrate entry)"
    text = skill.read_text()
    assert "user-invocable: true" in text
    # Scoped to the cutover subcommand + git, not arbitrary Bash.
    assert "Bash(prawduct-hook migrate-plugin*)" in text
    assert "Bash(...)" not in text and "Bash(*)" not in text


def test_hook_dispatches_migrate_plugin():
    src = HOOK.read_text()
    assert 'command == "migrate-plugin"' in src
    assert "migrate-plugin [--apply] [--json]" in src  # usage string


def test_migrate_nudges_point_at_existing_skill():
    # Chunk 8's nudges reference /prawduct:migrate — the skill must now back them.
    assert (ROOT / "skills" / "migrate" / "SKILL.md").is_file()
    assert "/prawduct:migrate" in (ROOT / "bin" / "prawduct-hook").read_text()


# =============================================================================
# Unit — _collapse_blank_runs (pure helper, imported in-process)
# =============================================================================


class TestCollapseBlankRuns:
    """Unit coverage for ``_collapse_blank_runs`` edge cases (TST-4H8M).

    Exercises the helper DIRECTLY (no subprocess) — it is a pure str→str
    function, so a subprocess round-trip would only add noise and couple these
    cases to the migrate dispatch wiring the other tests already cover.
    """

    @pytest.mark.parametrize(
        "n",
        [3, 4, 5, 7, 8, 12],
        ids=["run3", "run4", "run5", "run7", "run8", "run12"],
    )
    def test_run_of_n_newlines_collapses_to_two(self, n):
        # Any run of 3+ consecutive newlines (3, 4, 5, and 7+) collapses to
        # exactly two newlines (one blank line) regardless of run length.
        text = "a" + ("\n" * n) + "b"
        assert _migrate_plugin._collapse_blank_runs(text) == "a\n\nb"

    def test_only_newlines_input_collapses_to_two(self):
        # A string that is nothing but a long newline run collapses to exactly two.
        assert _migrate_plugin._collapse_blank_runs("\n" * 9) == "\n\n"

    def test_empty_string_is_unchanged(self):
        assert _migrate_plugin._collapse_blank_runs("") == ""

    def test_no_blank_run_is_unchanged(self):
        # A single blank line (two newlines) is already at the floor — untouched.
        assert _migrate_plugin._collapse_blank_runs("a\n\nb") == "a\n\nb"

    def test_while_loop_converges_across_multiple_runs(self):
        # The while-loop must collapse EVERY run, not just the first — two
        # separate triple-newline runs each reduce to a double newline.
        text = "a\n\n\nb\n\n\nc"
        assert _migrate_plugin._collapse_blank_runs(text) == "a\n\nb\n\nc"
